//
//  Prediction+CoreDataClass.swift
//  SkinSkan
//
//  Created by Brian Ooi on 11/14/22.
//
//

import Foundation
import CoreData

/// Class generated by Core Data to store Prediction results into persistent storage
@objc(Prediction)
public class Prediction: NSManagedObject {

}
